### ISSUE TITLE
Not an Issue more like a Suggestion.

### ISSUE THREAD

**Issue by SpiryMedia** [rafaelklaessen/react-tradingview-widget#17]
Would be awesome if the Technical Analysis would be added also into this package. 

https://www.tradingview.com/widget/technical-analysis/

I've tried to fork and do something, but I am noob at it. Just learning React.

**Comment by rafaelklaessen** [comment]
Hi SpiryMedia,

This package is only for rendering the Advanced Real-Time Chart widget, although it does "secretly" support some other widgets as well.

That being said, I do love the idea of adding the Technical Analysis widget!
However, the problem is that the way the Technical Analysis widget has to be embedded is completely different from the way the Advanced Real-Time Chart widget is embedded.
Because of this, adding the Technical Analysis widget would be quite hard and it also wouldn't be SSR compatible.

Would love to hear your thoughts.

Best,
Rafael

**Comment by SpiryMedia** [comment]
Hey Rafael, thanks for your time.

Can you give me an example of what other widgets supports? 

I managed to forcefully insert it by having in in document.jsx file basically directly injected in header . I tried so somehow the javascript must be called 100% INSIDE the div which makes it extremely hard to be SSR compatible. I've searched the whole google how to call that JS file + it's variables + it's div in one component. . I think axio would do? I don't know. I am a total beginner.

Thanks,
Spiry

**Comment by rafaelklaessen** [comment]
Hi Spiry,

I don't have a clue either. I might take a look at it soon but I'm quite busy at the moment.

Furthermore, regarding the other widgets: basically, all widgets called through `new TradingView[widgetType]` (like `new TradingView.widget` and `new TradingView.chart`) are supported through the `widgetType` prop.

Best,
Rafael
