### ISSUE TITLE
Cannot find out how to color the bottom bars

### ISSUE THREAD

**Issue by katerlouis** [rafaelklaessen/react-tradingview-widget#33]
Hey, I'm wondering if it's even possible to color these two parts of the widget.
If so, please tell me how :)

The options from this page don't seem to affect them
https://github.com/mmmy/css3demos/wiki/Overrides

![image](https://user-images.githubusercontent.com/1983382/62628416-91102f00-b92b-11e9-94bf-38c0ef18a34f.png)

**Comment by rafaelklaessen** [comment]
Hi, thanks for the issue!

Since this package is only a very simple wrapper around the [Advanced Real-Time Chart Widget](https://www.tradingview.com/widget/advanced-chart/) by TradingView, you'd have to refer to their documentation.

(Really, the only thing that this package does is provide a React variant of TradingView's API. Nothing is actually changed.)
